#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDashboard.Views.Dashboard
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Views\Dashboard\Login.cshtml"
    using LogDashboard.Extensions;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Dashboard\Login.cshtml"
    using LogDashboard.Models;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Views\Dashboard\Login.cshtml"
    using LogDashboard.StackTrace;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class Login : LogDashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral(@"<!DOCTYPE html>
<html lang=""zh-CN"">

<head>
    <meta charset=""UTF-8"">
    <meta name=""viewport"" content=""width=device-width, initial-scale=1"">

    <title>登录页</title>
    <meta name=""keywords"" content="""" />
    <meta name=""description"" content="""" />
    <link href=""");


            
            #line 16 "..\..\Views\Dashboard\Login.cshtml"
           Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/css.login.css\" rel=\"stylesheet\">\r\n    <link href=\"");


            
            #line 17 "..\..\Views\Dashboard\Login.cshtml"
           Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/css.bootstrap.min.css\" rel=\"stylesheet\">\r\n    <link href=\"");


            
            #line 18 "..\..\Views\Dashboard\Login.cshtml"
           Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/css.font-awesome.min.css\" rel=\"stylesheet\">\r\n</head>\r\n\r\n<body>\r\n\r\n    <div class" +
"=\"limiter\">\r\n        <div class=\"container-login\" style=\"background-image: url(\'" +
"");


            
            #line 24 "..\..\Views\Dashboard\Login.cshtml"
                                                              Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/image.login-bg.jpg\');\">\r\n\r\n            <div class=\"wrap-login p-l-55 p-r-55 p-t-" +
"65 p-b-54\">\r\n                <form id=\"login-form\" class=\"login-form validate-fo" +
"rm\">\r\n                    <span class=\"login-form-title p-b-49\">登录</span>\r\n\r\n   " +
"                 <div class=\"wrap-input validate-input m-b-23\" data-validate=\"请输" +
"入用户名\">\r\n                        <span class=\"label-input\">用户名</span>\r\n          " +
"              <input class=\"input\" type=\"text\" name=\"name\" placeholder=\"请输入用户名\" " +
"autocomplete=\"off\">\r\n                        <span class=\"focus-input\" data-symb" +
"ol=\"&#xf206;\"></span>\r\n                    </div>\r\n\r\n                    <div cl" +
"ass=\"wrap-input validate-input\" data-validate=\"请输入密码\">\r\n                        " +
"<span class=\"label-input\">密码</span>\r\n                        <input class=\"input" +
"\" type=\"password\" name=\"password\" placeholder=\"请输入密码\">\r\n                        " +
"<span class=\"focus-input\" data-symbol=\"&#xf190;\"></span>\r\n                    </" +
"div>\r\n\r\n                    <div class=\"text-right p-t-8 p-b-31\">\r\n             " +
"           <a href=\"javascript:\"></a>\r\n                    </div>\r\n\r\n           " +
"         <div class=\"container-login-form-btn\">\r\n                        <div cl" +
"ass=\"wrap-login-form-btn\">\r\n                            <div class=\"login-form-b" +
"gbtn\"></div>\r\n                            <button class=\"login-form-btn\" onclick" +
"=\"submitForm()\">登 录</button>\r\n                        </div>\r\n                  " +
"  </div>\r\n                </form>\r\n            </div>\r\n        </div>\r\n    </div" +
">\r\n    <script src=\"");


            
            #line 56 "..\..\Views\Dashboard\Login.cshtml"
            Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/js.jquery.min.js\"></script>\r\n    <script src=\"");


            
            #line 57 "..\..\Views\Dashboard\Login.cshtml"
            Write(Context.Options.PathMatch);

            
            #line default
            #line hidden
WriteLiteral("/js.login.js\"></script>\r\n</body>\r\n</html>");


        }
    }
}
#pragma warning restore 1591
