#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogDashboard.Views.Dashboard
{
    using System;
    
    #line 5 "..\..\Views\Dashboard\LogList.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 6 "..\..\Views\Dashboard\LogList.cshtml"
    using LogDashboard.Extensions;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Views\Dashboard\LogList.cshtml"
    using LogDashboard.Models;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class LogList : LogDashboard.Views.RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n\r\n");


WriteLiteral("\r\n");




WriteLiteral(@"

<div class=""table-responsive"">
    <table class=""table row mx-0"">
        <thead class=""w-100"">
            <tr class=""row mx-0"">
                <th class=""col-1"">Id</th>
                <th class=""col-3"">Logger</th>
                <th class=""col-1"">级别</th>
                <th class=""col-4"">消息</th>
                <th class=""col-2"">时间</th>
                <th class=""col-1"">详情</th>
            </tr>
        </thead>
        <tbody class=""w-100"">
");


            
            #line 23 "..\..\Views\Dashboard\LogList.cshtml"
             foreach (var item in (IEnumerable<ILogModel>)ViewData["Model"])
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr class=\"row mx-0\">\r\n                    <td class=\"col-1\"><a h" +
"ref=\"javascript:void(0);\" onclick=\"logInfo(\'");


            
            #line 26 "..\..\Views\Dashboard\LogList.cshtml"
                                                                                 Write(item.Id.ToString());

            
            #line default
            #line hidden
WriteLiteral("\')\">");


            
            #line 26 "..\..\Views\Dashboard\LogList.cshtml"
                                                                                                        Write(item.Id.ToString());

            
            #line default
            #line hidden
WriteLiteral("</a></td>\r\n                    <td class=\"col-3\">");


            
            #line 27 "..\..\Views\Dashboard\LogList.cshtml"
                                 Write(item.Logger);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"col-1\"><button class=\"btn btn-outline-");


            
            #line 28 "..\..\Views\Dashboard\LogList.cshtml"
                                                                Write(item.Level.ToString());

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 28 "..\..\Views\Dashboard\LogList.cshtml"
                                                                                        Write(item.Level.ToString());

            
            #line default
            #line hidden
WriteLiteral("</button></td>\r\n                    <td class=\"col-4\" onclick=\"$(this).next().sho" +
"w(); $(this).css(\'display\',\'none\');\">\r\n");


            
            #line 30 "..\..\Views\Dashboard\LogList.cshtml"
                          
                            var message = item.Message;
                            if (message.Length > 90)
                            {
                                message = message.Substring(0, 90) + "........";
                            }
                        

            
            #line default
            #line hidden
WriteLiteral("                        ");


            
            #line 37 "..\..\Views\Dashboard\LogList.cshtml"
                   Write(message);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </td>\r\n                    <td class=\"col-4\" style=\"display" +
": none;\" onclick=\"$(this).prev().show(); $(this).css(\'display\',\'none\');\">");


            
            #line 39 "..\..\Views\Dashboard\LogList.cshtml"
                                                                                                                        Write(item.Message);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"col-2\">");


            
            #line 40 "..\..\Views\Dashboard\LogList.cshtml"
                                 Write(item.LongDate.ToString("yyyy-MM-dd hh:mm:ss"));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td class=\"col-1\"><a href=\"javascript:void(0);\" onclic" +
"k=\"logInfo(\'");


            
            #line 41 "..\..\Views\Dashboard\LogList.cshtml"
                                                                                 Write(item.Id.ToString());

            
            #line default
            #line hidden
WriteLiteral("-info\',\'logInfoModal\',\'logInfoBody\')\">详情</a></td>\r\n                    <div style" +
"=\"display: none\" id=\"");


            
            #line 42 "..\..\Views\Dashboard\LogList.cshtml"
                                              Write(item.Id.ToString());

            
            #line default
            #line hidden
WriteLiteral("-info\">");


            
            #line 42 "..\..\Views\Dashboard\LogList.cshtml"
                                                                        Write(item.ToJsonString());

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                </tr>\r\n");


            
            #line 44 "..\..\Views\Dashboard\LogList.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral(@"        </tbody>
    </table>
</div>
<div class=""modal fade show"" id=""logInfoModal"" tabindex=""-1"">
    <div class=""modal-dialog modal-lg"">
        <div class=""modal-content"">
            <div class=""modal-header"">
                <h5 class=""modal-title"">日志详情</h5>
                <button type=""button"" class=""close"" data-dismiss=""modal"" aria-label=""Close"">
                    <span aria-hidden=""true"">×</span>
                </button>
            </div>
            <div class=""modal-body"" id=""logInfoBody"">

            </div>
        </div>
    </div>
</div>
");


        }
    }
}
#pragma warning restore 1591
